#this program will create ascii art for dices 

import random #we will still use the random library to randomise numbers rolled 

#we use unicode characters to draw asci art 
#we will use python here to enter . We first type in a "\" followed by seven unicode characters we will need to build some asci art 

#print("\u25CF \u250C \u2500 \u2510 \u2502 \u2514  \u2518") #These are the seven unicode characters that generate for us the asci art 
#this program will output these symbols that we will use the build our dices 
'''
● ┌ ─ ┐ │ └  ┘

'''

# we now start to build the dices using the characteres generated by the unicode 

"┌─────────┐"
"│         │"
"│         │"
"│         │"
"└─────────┘"

#we now create a dictionary of key value pairs containing tuples 
diceArt = {
    1: ("┌─────────┐",
        "│         │",
        "│    ●    │",
        "│         │",
        "└─────────┘"
        ),

    2: ("┌─────────┐",
        "│ ●       │",
        "│         │",
        "│       ● │",
        "└─────────┘"
        ),

    3: ("┌─────────┐",
        "│ ●       │",
        "│    ●    │",
        "│       ● │",
        "└─────────┘"
        ),
    
    4: ("┌─────────┐",
        "│ ●     ● │",
        "│         │",
        "│ ●     ● │",
        "└─────────┘"
        ),

    5: ("┌─────────┐",
        "│ ●     ● │",
        "│    ●    │",
        "│ ●     ● │",
        "└─────────┘"
        ),

    6: ("┌─────────┐",
        "│ ●     ● │",
        "│ ●     ● │",
        "│ ●     ● │",
        "└─────────┘"
        )
}

dice = []
total = 0
num_of_dice  = int (input("How many dice ? : "))#so that a user doesnt enter decimals 

for die in range(num_of_dice):
    dice.append(random.randint(1,6))#to generate a random number from 1 to 6 
    #appending the  random number into our list 

#this loop will generate our asci art 
for die in range(num_of_dice):
    for line in diceArt.get(dice[die]):#this loop prints every tuple
        print(line)

#this loop will print the asci art horizontally 
for line in range(5):
    for die in dice:
        print(diceArt.get(die)[line], end = "")
    print()


#this loop adds up whatever is in the list of dice 
for die in dice :
    total += die

print(f"Total: {total}")


